name=Wire
version=1.0.0
author=Your Name
maintainer=Your Name <your@email.com>
sentence=This library allows you to communicate with I2C and Two Wire Interface devices.
paragraph=Specific implementation for the Arduino Core Template boards.
category=Communication
url=https://github.com/carlosperate/ArduinoCore-Template
architectures=template-arch
includes=Wire.h
