name=SPI
version=1.0.0
author=Your Name
maintainer=Your Name <your@email.com>
sentence=Enables the communication with devices that use the Serial Peripheral Interface (SPI) Bus.
paragraph=Specific implementation for the Arduino Core Template boards.
category=Communication
url=https://github.com/carlosperate/ArduinoCore-Template
architectures=template-arch
includes=SPI.h
