name: Code Style Checker

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  style-checker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run local action clang-format
      uses: ./.github/actions/clang-format
      with:
        args: --recursive . --style=file
